skip_branch_with_pr: true

image:
  - Visual Studio 2017
  - ubuntu

cache:
  - c:\tools\vcpkg\installed\

install:
  - pwsh: |
      if ($isLinux) {
        ./install.linux.ps1
      } else {
        ./install.windows.ps1
      }

build_script:
  - pwsh: |
      if ($isLinux) {
        ./build.linux.ps1
      } else {
        .\build.windows.ps1 -VcpkgToolchain c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake
      }

after_build:
  - pwsh:
      if ($isLinux) {
        ./pack.linux.ps1
      } else {
        .\pack.windows.ps1
      }

artifacts:
  - path: tdlib.windows.zip
    name: tdlib.windows
  - path: tdlib.linux.zip
    name: tdlib.linux

deploy:
  provider: GitHub
  auth_token:
    secure: 5a702IC4V2Pma89YLOuYk6aPqu5MGDUQLMcky9+XjkLInN6D8YKYQfDQ67f5RdpU
  artifact: tdlib.windows,tdlib.linux
  on:
    APPVEYOR_REPO_TAG: true
